---
- name: Configure grub to for plymouth
  template:
    src: default-grub.j2
    dest: /etc/default/grub
  notify: Update grub2 generated files
  become: yes

- name: Disable stable interface names
  lineinfile:
    path: /etc/default/grub
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0"'
    insertafter: '^GRUB_CMDLINE_LINUX'
  notify: Update grub2 generated files
  become: yes

- name: Add graphic driver modules to initramfs
  lineinfile:
    path: /etc/initramfs-tools/modules
    line: "{{ item }}"
  with_items: "{{ initramfs_modules }}"
  notify: Update initramfs
  become: yes

- name: Configure plymouth
  template:
    src: plymouth.conf.j2
    dest: /etc/plymouth/plymouth.conf
  notify: Update initramfs
  become: yes

- name: Create systemd getty directory
  file:
    path: /etc/systemd/system/getty@tty1.service.d/
    recurse: yes
    state: directory
  become: yes

- name: Setup autologin as {{ autologin_user }}
  template:
    src: tty-override.conf.j2
    dest: /etc/systemd/system/getty@tty1.service.d/override.conf
  become: yes

- name: Create /opt/kiosk/ directory
  file:
    path: /opt/kiosk
    recurse: yes
    state: directory
  register: kiosk_dir_result
  become: yes

- name: Copy files from {{ kiosk_user_home_dir }} to /opt/kiosk
  synchronize:
    src: "{{ kiosk_user_home_dir }}/"
    dest: /opt/kiosk
  delegate_to: "{{ inventory_hostname }}"
  when: kiosk_user_home_dir_sync
  become: yes

- name: Configure user for midori kiosk start up
  template:
    src: xsessionrc.j2
    dest: /opt/kiosk/.xsessionrc
  become: yes

- name: Install scripts for midori kiosk start up
  copy:
    src: "{{ item }}"
    dest: "/opt/kiosk/.{{ item }}"
  become: yes
  with_items:
    - bash_logout
    - bashrc
    - profile

- name: Set owner of kiosk files.
  file:
    dest: /opt/kiosk
    owner: "{{ autologin_user }}"
    group: "{{ autologin_group }}"
    mode: 0744
    recurse: yes
  become: yes

- name: Copy scripts to {{ kiosk_user_home_dir }}
  copy:
    src: "/opt/kiosk/{{ item }}"
    dest: "{{ kiosk_user_home_dir }}/{{ item }}"
    remote_src: yes
  become: yes
  with_items:
    - .bash_logout
    - .bashrc
    - .profile
    - .xsessionrc

- name: Set owner of kiosk files in {{ kiosk_user_home_dir }}
  file:
    dest: "{{ kiosk_user_home_dir }}/{{ item }}"
    owner: "{{ autologin_user }}"
    group: "{{ autologin_group }}"
    mode: 0744
  become: yes
  with_items:
    - .bash_logout
    - .bashrc
    - .profile
    - .xsessionrc
