---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Install OS-specific packages
  include_tasks: "{{ ansible_os_family }}-install.yml"

- name: Configure OS-specific settings
  include_tasks: "{{ ansible_os_family }}-config.yml"
