---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install OS-specific packages
  include_tasks: "{{ ansible_distribution }}-install.yml"

- name: Configure OS-specific settings
  include_tasks: "{{ ansible_distribution }}-config.yml"
