---
- name: Update apt cache.
  apt:
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: Install Ubuntu packages needed for the midori kiosk installation.
  apt:
    name: "{{ item }}"
    state: "{{ kiosk_packagess_state }}"
  with_items: "{{ kiosk_packages }}"
  become: yes
